package main

import (
	"context"
	"fmt"
	"log/slog"
	"os"
	"os/signal"
	"syscall"

	"github.com/Tarun516/anzu-agent-runtime/internal/config"
	"github.com/Tarun516/anzu-agent-runtime/internal/health"
	"github.com/Tarun516/anzu-agent-runtime/internal/storage"
)

// main is the operating-system entrypoint for anzu-realtime.
//
// It creates process-level dependencies, runs the application,
// and decides the final process exit code.
func main() {
	// 1. Create the structured logger used by this process.
	logger := slog.New(
		slog.NewJSONHandler(
			os.Stdout,
			nil,
		),
	)

	// 2. Run the application lifecycle.
	if err := run(logger); err != nil {
		// 3. Record the fatal application error.
		logger.Error(
			"realtime service failed",
			"error",
			err,
		)

		// 4. Exit with a non-zero code to indicate failure.
		os.Exit(1)
	}
}

// run owns the lifecycle of the realtime process.
//
// Keeping lifecycle management outside main allows deferred
// cleanup to execute before control returns to main.
func run(logger *slog.Logger) error {
	// 1. Load and validate service configuration.
	cfg, err := config.LoadService(
		"realtime",
		":8081",
	)
	if err != nil {
		return fmt.Errorf(
			"load realtime configuration: %w",
			err,
		)
	}

	// 2. Load and validate PostgreSQL configuration.
	dbCfg, err := config.LoadDatabase()
	if err != nil {
		return fmt.Errorf(
			"load database configuration: %w",
			err,
		)
	}

	// 3. Create the root application context.
	//
	// SIGINT is commonly generated by Ctrl+C.
	// SIGTERM is commonly used by Docker, systemd,
	// and other process managers.
	ctx, stop := signal.NotifyContext(
		context.Background(),
		os.Interrupt,
		syscall.SIGTERM,
	)
	defer stop()

	// 4. Create the PostgreSQL connection pool
	// and verify initial database connectivity.
	db, err := storage.OpenPostgres(
		ctx,
		dbCfg,
	)
	if err != nil {
		return fmt.Errorf(
			"initialize PostgreSQL: %w",
			err,
		)
	}

	// 5. The process owns the pool, so close it
	// when the process lifecycle finishes.
	defer db.Close()

	// 6. Record successful database initialization.
	//
	// Do not log the database URL because it may
	// contain credentials.
	logger.Info(
		"database connected",
		"service",
		cfg.Name,
	)

	// 7. Construct the health server and inject
	// every dependency required to accept new work.
	server := health.NewServer(
		cfg.Name,
		cfg.Address,
		cfg.ShutdownTimeout,
		logger,
		[]health.ReadinessCheck{
			{
				Name:  "postgres",
				Check: db.Ping,
			},
		},
	)

	// 8. Process initialization completed successfully,
	// so the lifecycle gate can now accept new work.
	server.SetReady(true)

	// 9. Record that the service is entering
	// its normal running state.
	logger.Info(
		"service starting",
		"service",
		cfg.Name,
		"address",
		cfg.Address,
	)

	// 10. Run until the HTTP server fails
	// or application cancellation begins.
	if err := server.Run(ctx); err != nil {
		return fmt.Errorf(
			"run realtime service: %w",
			err,
		)
	}

	// 11. Record successful completion of graceful shutdown.
	logger.Info(
		"service stopped",
		"service",
		cfg.Name,
	)

	return nil
}
